### ISSUE TITLE
[Feature Request] Explicit role_arn along aide role_name

### ISSUE THREAD

**Issue by ali4579** [aws-ia/taskcat#618]
Hi Taskcat  people, I know this isn't really the place for tech support,  but I can see role_arn was added in 0.9.19, but I cannot find any information  on how to use it.

I am attempting to have a codebuild in one account build a taskcat stack in another account. I added role_name: to my config file in the project section and gave the arn of the role I want it to assume. I ran taskcat with debug on, and I see no evidence of taskcat assuming that role. The cloudformation stack launches in the parent account, a "-" in the IAM Role of the taskcat stack and there's nothing in cloudtrail about a role switch. What I expected was to see the role_arn in the IAM Role of the taskcat stack, and the stack itself launching in the child account. 

I have tried using taskcat in a codebuild (so an instance role) and via a profile on a Mac (configured with aws configure). Taskcat is installed with pip and in both instances the taskcat version is 0.9.20

Any help you can give would be appreciated please and I'm happy to help amend the documentation :)

My config file is:

project:
  owner: myemail@address.com
  name: ali-lifecycle3
  regions:
    - ap-southeast-2
  role_name: arn:aws:iam::<accountID>:role/assembly-line-roles-cross-account-role
  s3_bucket: dbtp-1389-staging
tests:
  default:
    template: singleServerStackLinux.dev.yaml

**Comment by andrew-glenn** [comment]
Hey @ali4579 , 

The intent was not necessarily to support a _cross-account_ role, but an inter-account role with specific permissions. Cross-account role would require that the launching role (ie, the creds you use to invoke taskcat with) has the appropriate AssumeRole permissions. 

The current implementation is to support a role name, and the underlying Role ARN is constructed. While this seems counter-intuitive on the surface, it does allow us to construct the ARN in the context of the region. This is important because we support per-region credentials, via `auth`. It's not something we think is a common use case, but it is something we need to support.

So, RoleName -> `aws:<region partition>:<region account>:iam:role/<role name>`. 
- I may not have the order correct, but this is for illustrative purposes.

Based on your question, I believe you'll benefit from none of this interpolation and would prefer a `role_arn` config option. This would be a passthrough option and we wouldn't go through the effort to construct it further. It'll do exactly what you tell it to do - and subsequently fail spectacularly if the AssumeRole call (from the CFN service) doesn't work.

The sharp edges this option would cause discouraged me from that when I was adding `role_name`. I'm happy to add `role_arn` with heavy "Be careful" documentation.

As an aside, if you're feeling up for it, I'll totally take you up on your documentation offer that covers my ramblings above! 👍

**Comment by ali4579** [comment]
Hi Andrew

Thanks for the fast response! We would LOVE role_arn, and we promise to be careful :). Taskcat is forming a really central place in our CICD system so this will be huge for us. 

I'll make some time to add some documentation on role_name and role_arn when it appears. Thank you so much :)

**Comment by ali4579** [comment]
Hi Andrew

You can cancel the request for role_arn, I've figured out a better (more correct?) way to do this - using role assumption in the boto profile to do the cross account, and then using role_name in taskcat to assume the cloudformation code. When I've got my act together I'll write a proper document on how to do it and perhaps it can be included in your examples somewhere if you're interested.

I notice you've giveen the label bugbash so perhaps you've figured this out, unfortunately role_name doesn't seem to be working. I've made it work by forking the taskcat code and attaching role_name to an object at the right time - I'm sure that's totally the wrong way to do it but it gets me going for now.

Thank you

Ali

**Comment by andrew-glenn** [comment]
@ali4579 

Hey Ali,

The bugbash label is a list of stuff I want to get done when everything else settles down around Thanksgiving. 

If you don't mind - I'm not sure I'm aware what's broken with `role_name`. Would you mind bringing me up to speed? Not necessarily looking for a PR, although I'll welcome one if you're feeling up to it. Just a quick mind share around what you found.

Leaving this open for now. I really appreciate your feedback! It makes working on a project like this worth the effort. 👍

**Comment by ali4579** [comment]
Hi Andrew

Just a quick note to say I haven't forgotten about this. We've got a pretty big (for us)  release happening right now and there's no time for anything else. I ended up forking taskcat and adding a couple of lines to fix it just for us and I'll show you the problem sometime soon.

Thanks

Ali

**Comment by ali4579** [comment]
Happy New Year!! I'm back, and ready to tell you about my role_name woes ;)

I've grabbed the latest version of taskcat and confirmed our issue is still happening. Hope I've given enough info below to show you what's happening. You can see the fork of taskcat that I'm using as a workaround here: https://github.com/ali4579/taskcat/tree/latest

There's also an override in that branch to use a regional sts endpoint as taskcat will fail for us without it due to SCP's (I'll log that issue another day...)

We are using codebuild to run taskcat. We are trying to use role_name to have taskcat use a specific role to launch taskcat

When I run taskcat, and check the created stack, no custom role is used.

If I then edit file _config.py, and change this line:
#                    _role_name=test.role_name,
to
                     _role_name=self.config.project.role_name,

And rerun taskcat, it assumes the role correctly.

I've included config files below. I hope I've given enough info to illustrate the problem, happy to provide you with YAML etc if you need it to help set up a codebuild project, roles, etc.

Ali

My taskcat config (likely has some unneeded lines)
general:
  auth:
    ap-southeast-2: taskcat
project:
  owner: cloudservices-dl@curtin.edu.au
  name: testtaskcat
  regions:
    - ap-southeast-2
  role_name: aliCloudformationExecutionRole
tests:
  assemblyline:
    auth:
      default: taskcat
      template: aliTestPattern.dev.yaml
    regions:
      - ap-southeast-2


My .aws/config file:
[profile taskcat]
role_arn=arn:aws:iam::REMOVED:role/aliCodeBuildExecutionRole
credential_source=EcsContainer
sts_regional_endpoints=regional
region=ap-southeast-2

**Comment by andrew-glenn** [comment]
It's an inheritance issue. 100%.


We've designed taskcat (in good faith) so that all the attributes bubble down to the Test object. Looks like that's not occurring here

Thanks for tracking it down! I'll grab a cup of coffee and see what's going on.

**Comment by ali4579** [comment]
Thank you Andrew!
