### ISSUE TITLE
How to pass random values for certain parameter in taskcat file

### ISSUE THREAD

**Issue by nitinitare** [aws-ia/taskcat#797]
When I am creating multiple resources through AWS codepipeline, all the builds will trigger at same time and only one build succeeds and other fails with error the resource already exist. 
I have only one .taskcat.yml file which is in the same folder as cloudformation template. And I have multiple .json parameters file in a different folder to create multiple resource.

Is there any way to pass random values for a parameter like resourcename(can be a s3 bucket, dynamodb table, rds, iam role etc)?

Let me know if there is a workaround.

**Comment by tlindsay42** [comment]
In infrastructure as code (IaC), naming is best implemented through tags/metadata rather than resource names to avoid situations like that, but there are ways to accomplish what you want, such as using [taskcat pseudo parameters](https://aws-ia.github.io/taskcat/docs/usage/PSUEDO_PARAMETERS/) like `$[taskcat_random-string]` and/or appending either all or part of the stack ID (using [CloudFormation intrinsic functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) like sub, split, join, et cetera).
